FROM golang:1.21-alpine

RUN apk add --no-cache \
    python3 \
    py3-pip \
    bash \
    git \
    gcc \
    libc-dev \
    python3-dev

RUN python3 -m venv /app/venv
ENV PATH="/app/venv/bin:$PATH"

ADD ./requirements.txt /app/
RUN pip3 install -r /app/requirements.txt
RUN rm /app/requirements.txt

#RUN mkdir -p /app/jobs
RUN mkdir -p /app/examples
ADD wiki.job wiki_history.job wiki_pageviews.py /app/examples

RUN git clone git@github.com:andrewbrdk/Repeater.git
WORKDIR /Repeater
RUN go get repeater
RUN go build
WORKDIR / 
RUN cp /Repeater/repeater /app/
RUN rm -r /Repeater

EXPOSE 8080

ENTRYPOINT ["/app/repeater"]
