FROM golang:1.23-alpine

RUN apk add --no-cache \
    bash \
    git

RUN git clone https://github.com/andrewbrdk/Outliers
WORKDIR /Outliers
RUN go get outliers
RUN go build
WORKDIR /
RUN cp /Outliers/outliers /app/outliers
RUN rm -r Outliers

EXPOSE 9090

ENTRYPOINT ["/app/outliers"]
