FROM golang:1.23-alpine

RUN apk add --no-cache \
    bash \
    git

RUN git clone https://github.com/andrewbrdk/Outliers /Outliers
WORKDIR /Outliers
RUN go get outliers
RUN go build
WORKDIR /
RUN mkdir -p /app
RUN cp /Outliers/outliers /app/outliers
RUN rm -r Outliers
WORKDIR /app
ADD outliers.toml ./

EXPOSE 9090

ENTRYPOINT ["/app/outliers"]
